B2U min/max_advance_offset doc updates
MyAllocator/build2us-apidocs pull request #4
Opened 2023-03-30 23:17 UTC by asarcb

This PR adds some more docs to min/max_advanced_offset, such as valid value >= 0, with 0 meaning no restriction. Also small changes in wording.

2023-04-03 10:57 UTC, cloudbeds-mo requested changes

2023-04-03 10:57 UTC, cloudbeds-mo commented on b2u-combined.yaml
> +                              which is the default. This restirction is mainly
typo in "restirction". below as well

2023-04-03 19:47 UTC, asarcb commented on b2u-combined.yaml
> +                              which is the default. This restirction is mainly
Fixed

2023-04-04 09:54 UTC, cloudbeds-mo approved these changes

2024-05-02 13:33 UTC, cloudbeds-mo approved these changes

2024-05-02 13:33 UTC, merged